Test.md
=> add Test.md

LICENSE, README.md, Thanks.md
修改和新增了以下内容：
- 修改了 README.md 里面的贡献者信息
- 新增了一个 Hexo logo
- 新增了 CC BY-NC-ND 4.0 许可信息的文件
- 在 Thanks.md 中新增了大佬板块
努力！💪
=> 🚀 优化和修改了一些地方

README.md
=> Update README.md (By markjuruo)

docs/1-Hexo-install-and-config/1-3-deploy.md
=> :memo: add post 1-3-deploy.md by MoshiYeap

docs/1-Hexo-install-and-config/1-3-deploy-hexo.md
Modify Edit 1-3-deploy-hexo 
Unified document 1-3 format
=>  📝 Finish writing Hexo-deploy

README.md, docs/README.md
=> Fix Github Links

README.md, package.json
1. Add build status badge. Data from travis-ci.
2. Change `package.json`'s name and description.
More info in commit message.
=> 👷 Add build status badge; Tweak `package.json` contents.

docs/1-Hexo-install-and-config/README.md
=>  📝 add  post 1-5 links by MoshiYeap

docs/1-Hexo-install-and-config/1-4-deploy-hexo.md
Edit the article syntax highlighting sh->bash
=>  📝 Edit somethings by MoshiYeap

Test.md, docs/1-Hexo-install-and-config/1-2-install-hexo.md
=> :clap: add arch install by yi-yun

docs/1-Hexo-install-and-config/1-4-deploy-hexo.md
Edit post 1-4 update git config
=>  📝 Edit post 1-4 update git config by MoshiYeap

docs/.vuepress/components/deploy.vue, docs/.vuepress/components/init.vue, docs/.vuepress/components/write.vue
总共三个视频，例如在要插入的地方 markdown 中引用<init />即可
=> :clap: add video setting by yi-yun

README.md
=> :blue_book: Update README.md

docs/2-Theme-use-and-config/2-10-hexo-theme-indigo/README.md
=> Modify post: '2-10-hexo-theme-indigo'

docs/2-Theme-use-and-config/2-7-hexo-theme-bmw/README.md
=> Modify post: '2-7-hexo-theme-bmw'

Contributors.md
=> :blue_book: Add new members in Contributors.md

.editorconfig, docs/.vuepress/components/dplayer.vue, docs/.vuepress/config.js, docs/1-Hexo-install-and-config/1-4-deploy-hexo.md
_如题_
PS：部署的教程视频被我换成了我自己的，麻烦告知原作者把视频放在一个可以**跨域**的网站然后换过来
=> 添加 dplayer 播放器支持

docs/2-Theme-use-and-config/2-10-hexo-theme-indigo/README.md
Add badge to post: '2-10-hexo-theme-indigo'.
=> :momo: Modify post: '2-10-hexo-theme-indigo'

docs/.vuepress/config.js, docs/.vuepress/theme/Comment.vue, docs/.vuepress/theme/Page.vue
=> Add algolia search support

README.md
添加了使用 emojikey 来说明贡献者做了什么的一个例子。
=> :blue_book: Add emojikey

docs/.vuepress/styles/palette.styl, docs/.vuepress/theme/styles/config.styl
=> Fixed a bug

docs/.vuepress/config.js, docs/2-Theme-use-and-config/2-1-hexo-theme-next-5.x.x/README.md, docs/2-Theme-use-and-config/2-10-hexo-theme-indigo/README.md, docs/2-Theme-use-and-config/2-11-hexo-theme-melody/README.md, docs/2-Theme-use-and-config/2-2-hexo-theme-next-6.x.x/README.md, docs/2-Theme-use-and-config/2-3-hexo-theme-yilia/README.md, docs/2-Theme-use-and-config/2-4-hexo-theme-apollo/README.md, docs/2-Theme-use-and-config/2-5-hexo-theme-material/README.md, docs/2-Theme-use-and-config/2-6-hexo-theme-material-x/README.md, docs/2-Theme-use-and-config/2-7-hexo-theme-bmw/README.md, docs/2-Theme-use-and-config/2-8-hexo-theme-aero-dual/README.md, docs/2-Theme-use-and-config/2-9-hexo-theme-amber/README.md
=> 🍔 Update posts

Contributors.md, docs/.vuepress/config.js, docs/1-Hexo-install-and-config/1-4-deploy-hexo.md, docs/5-Add/5-3-date-file.md
📝 add post 5-3-data-file e0e7203
📝 update author blog link 4863836
=> 📝 add post 5-3-data-file and update MoshiYeap blog link

docs/1-Hexo-install-and-config/1-4-deploy-hexo.md
updata post 1-4 deoploy-hexo 38fed0f
1. 修改部分措辞。
2. 为部分有A记录需求的用户增加了如何设置A记录的指向链接。（不排除部分用户对A记录有需求）
3. 更正CNAME拼写。
=>  📝 updata post 1-4 deoploy-hexo

docs/2-Theme-use-and-config/2-9-hexo-theme-amber/README.md
=> 📄 Update 2-9-hexo-theme-amber

.travis.yml
=>  📝 change target-branch master

docs/.vuepress/config.js
=>  🔧 add google-analytics

docs/README.md
=>  📝 updata Home page content

Contributors.md, docs/.vuepress/config.js, docs/2-Theme-use-and-config/2-12-hexo-theme-icarus/README.md
=> ✨ Add hexo-theme-icarus

.gitignore, .travis.yml, docs/1-Hexo-install-and-config/1-4-deploy-hexo.md, package-lock.json
1. Solve the problem of invalid custom domain name caused by the lack of CNAME file in the local source directory.
2. locked package.json
3. reconfig ci seting
=> ✨ cancel ignore package-lock.json

.travis.yml, docs/.vuepress/config.js, package.json
增加站点地图sitemap插件
Signed-off-by: MonoLogueChi
=> 添加 vuepress-plugin-sitemap 插件

docs/1-Hexo-install-and-config/1-5-continuous-integration.md
1. Add some of the explanation to the .travis.yml annotation
2. Remove `npm install`
3. Remove `install libpng16-dev`
4. Changed `npm install hexo-cli -g`-->>`npm install hexo-cli`
=> ✨ Modified post 1-5

docs/2-Theme-use-and-config/2-12-hexo-theme-icarus/README.md
=> 📝 Update README.md

Contributors.md, docs/.vuepress/_config.yml, docs/0-Intro/0-1-member.md, docs/2-Theme-use-and-config/2-14-hexo-theme-matery/README.md
解决 #153 
添加 matery 主题的内容。感谢 blinkfox :heart:
下一步将会把图片搬回项目本地。
=>  💎 Add hexo-theme-matery & Add blinkfox into Contributors

docs/.vuepress/_config.yml, docs/3-Plugins-use-and-config/3-3-hexo-helper-live2d/README.md, docs/3-Plugins-use-and-config/3-4-hexo-blog-encrypt/README.md, yarn.lock
1. 添加了 #159 提出的 hexo-blog-encrypt 插件内容，感谢 @WhiteSnowPinkPinkWhatItLike 。
2. ~~修复了 #170 的 bug，感谢 @AlliotTech 。~~
=> Add new post

yarn.lock
=> 📦 Update yarn.lock
